CREATE TABLE HIVE_CONNECTION (
  CONNECTION_NAME    	 VARCHAR(255)  NOT NULL,
  DRIVER_CLASS           VARCHAR(255)  NOT NULL,
  CONNECTION_URI    	 VARCHAR(255)  NOT NULL,
  FILESYSTEM_URI    	 VARCHAR(255),
  DESCRIPTION            TEXT,
  PRIMARY KEY (CONNECTION_NAME)
) DEFAULT CHARSET='utf8'; 

CREATE TABLE HIVE_QUERY_CATEGORY (
  CATEGORY_NAME          VARCHAR( 50)  NOT NULL,
  CREATOR_NAME           VARCHAR( 50)  ,
  PRIMARY KEY (CATEGORY_NAME)
) DEFAULT CHARSET='utf8' ;

CREATE TABLE HIVE_QUERY (
  QUERY_ID               INT  UNSIGNED NOT NULL AUTO_INCREMENT,
  QUERY_NAME             VARCHAR(100)  NOT NULL UNIQUE,
  CATEGORY_NAME          VARCHAR( 50)  NOT NULL DEFAULT 'default',
  QUERY                  TEXT          NOT NULL,
  CREATOR_NAME           VARCHAR( 50)  ,
  CREATE_DATE            DATETIME      ,
  DESCRIPTION            VARCHAR(255)  ,
  PRIMARY KEY (QUERY_ID)
) DEFAULT CHARSET='utf8' ;

CREATE TABLE QUERY_TASK (
  TASK_ID                VARCHAR( 50)  NOT NULL, 
  USER_NAME              VARCHAR( 50)  ,
  FINISHED               VARCHAR( 10)  ,
  ERROR                  VARCHAR( 10)  ,
  STATUS                 VARCHAR( 10)  ,
  START_TIME             DATETIME      ,
  END_TIME               DATETIME      ,
  CONNECTION_NAME        VARCHAR(255)  ,
  RESULT_PATH            VARCHAR(255)  ,
  SAVE_RESULT            BOOLEAN       ,
  QUERY                  TEXT          ,
  ERROR_MESSAGE          TEXT          ,   
  PRIMARY KEY (TASK_ID)
) DEFAULT CHARSET='utf8' ;

CREATE TABLE HIVE_USER (
  USER_ID                VARCHAR( 50)  NOT NULL, 
  PASSWORD               VARCHAR( 50)  NOT NULL,
  PRIMARY KEY (USER_ID)
) DEFAULT CHARSET='utf8' ;


INSERT INTO HIVE_USER VALUES('admin', password('admin'));  